Extensions\Bundle\MappingConnectorBundle\Entity\Mapping:
    properties:
        code:
            - NotBlank: ~
        attribute:
            - NotBlank: ~
        title:
            - NotBlank: ~
        job:
            - NotBlank: ~