extensions:
    pim-menu-settings-mapping:
        module: pim/menu/item
        parent: pim-menu-settings-navigation-block
        position: 500
        config:
            title: extensions_mapping_connector.menu.item.reference_data.mapping
            to: pim_customentity_index
            routeParams:
                customEntityName: mapping